name: auto-merge-scenario-A

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-merge:
    - name: merge main-branch into release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository release branch
        uses: actions/checkout@v3
        with:
          ref: release
        run: echo release branch was checkouted.
      - name: Merge main-branch into release-branch
        run: git merge main
