name: auto-merge-scenario-A

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-merge-a:
    name: merge main-branch into release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository release branch
        uses: actions/checkout@v3
      - name: Merge main to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release-scenario-A
          git merge main
          git push origin release-scenario-A --force
