name: auto-merge-scenario-A

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  auto-merge-a:
    name: merge main-branch into release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository release branch
        uses: actions/checkout@v3
      - name: create PR from main to release
        run: gh pr create -B release -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
